apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-demo-api
  template:
    metadata:
      labels:
        app: argo-demo-api
    spec:
      containers:
      - image: ghelobytes/argo_demo_image:v1
        name: argo-demo-api
        ports:
        - containerPort: 80