apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo_demo_api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo_demo_api
  template:
    metadata:
      labels:
        app: argo_demo_api
    spec:
      containers:
      - image: docker.com/ghelobytes/argo_demo_image:v1
        name: argo_demo_api
        ports:
        - containerPort: 80